### ISSUE TITLE
How many tracking events can we handle?

### ISSUE THREAD

**Issue by aquilesC** [privalytics/Lean-Privalytics#6]
We can measure the time it takes to store each post request.

- [x] Add Model to Log the time of each post request
- [x] Use nginx to log response times
- [x] Make statistics about times

**Comment by aquilesC** [comment]
We can also use https://locust.io/ to test the response of our server

**Comment by aquilesC** [comment]
I have analyzed what I have up to this point [here](https://github.com/privalytics/Technical-Notes/blob/master/AnalysingResponseTime.ipynb). The tracking is not a problem (~20ms per event), but the dashboard generation consumes up to 1 second. 

Tracking can easily go to 200/s (4 workers), which is 518e6 requests per month (518 *advanced* subscriptions). 

Dashboard generation, at 1/s is still 10e6 requests per month. The problem is the inhomogeneity in time distribution, if most people visit the website at the same time ranges, etc.
